version: '3.6'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./SampleCollections:/usr/local/sampleCollections
      - mongo-data:/data/db
    working_dir: /usr/local/sampleCollections

  server:
    image: node:alpine
    volumes:
      - ./server:/usr/local/server
    working_dir: /usr/local/server
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://root:password@mongo:27017/app?authSource=admin
      - DB_URL=postgres://root:password@db/app
      - JWT_SECRET=mySecret
    ports:
      - 127.0.0.1:3000:3000
    command: npm start

  client:
    image: node:alpine
    volumes:
      - ./client:/usr/local/server
    working_dir: /usr/local/server
    environment:
      - REACT_API_URL=http://server:3001
      - CLIENT_PORT=3001
      - CLIENT_HOST=0.0.0.0
    ports:
      - 127.0.0.1:3001:3001
    command: npm start

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - 5432:5432
volumes:
  mongo-data: {}
  db-data: {}