###

GET http://localhost:3000/users/users-list

###
POST http://localhost:3000/users/users
Content-Type: application/json

{
    "email": "Slimane@Symfony.com",
    "password": "azertyuiop",
    "firstName": "Slimane",
    "lastName": "Symfony",
    "role": "admin"
}